### PR TITLE
Update amd64.src

### PR DESCRIPTION
**Pull request by LapaJr31**
New SHA256 key for this release

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Too bad :(

I don't think it's Debian 11-compatible anymore.

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
https://paste.yunohost.org/raw/ojenezubop

> Couldn't parse SOURCE_URL from /var/cache/yunohost/app_tmp_work_dirs/app_w5sabj7y/conf/arm64.src ?

**Comment by lapineige** [comment]
Why ? :(

**Comment by LapaJr31** [comment]
Oh God I completely forgot about this

**Comment by LapaJr31** [comment]
Reopen button doesn't work for me(

**Comment by lapineige** [comment]
Because the head branch (the fork ?) was deleted

**Pull request closed without merging**
