### PR TITLE
testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Thanks, I forgot to prepare that PR :smile:

However, it's not a sha256sum fix, it's a new update. I changed the version number.

**Comment by lapineige** [comment]
I forgot to explain that I would have preferred to manually test it first, as those update changes can't be really assessed with the CI.
Anyway I just done it, it works well, great, thanks for the PR :slightly_smiling_face:

**Comment by lapineige** [comment]
Oh no in fact there is some issues…

In particular this is causing an error : `/var/www/akkoma/live/lib/fast_html-2.2.0/priv/fasthtml_worker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/www/akkoma/live/lib/fast_html-2.2.0/priv/fasthtml_worker)`

**Comment by lapineige** [comment]
Libc6 is in version 2.31-13+deb11u6

**Comment by lapineige** [comment]
I'm afraid that will mean we have to build our own updates until Debian 12 is supported by Yunohost.
And that fresh installs will fail.

**Pull request merged**
