### PR TITLE
[Testing] Change config file on install to enable admin UI configuration + install mangane

### LINKED ISSUE #6: Configurable_from_database disabled
I managed to install Akkoma with Yunohost, inlog and posting works fine.
But upon entering the administrative backend (https://my-domain.tld/pleroma/admin/#/users/index) I get this error:

"Request failed with status code 400 - You must enable configurable_from_database in your config file."

I will look for a solution with Akkoma support also, but was wondering if its a flaw in the install script.

### PR DESCRIPTION
**Pull request by lapineige**
Fixes #6

- [ ] Should do it on upgrade and restore too ?
- [ ] We should document Mangane in the readme.

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by bugsysop** [comment]
Look at Pleroma YNH install script. 
https://github.com/YunoHost-Apps/pleroma_ynh/blob/master/scripts/install

In line 211 we have:

```
ynh_replace_string --match_string="config :pleroma, configurable_from_database: false" --replace_string="config :pleroma, configurable_from_database: true" --target_file="$config"
```
This replace le default string in config file ("configurable_from_database: false") to activate the confing in DB.

This is must done _before_ Akkoma is running!

Later/after (at the end of install script) we have to run:

```
ynh_exec_warn_less ynh_exec_as $app -s $SHELL -lc "$final_path/live/bin/pleroma_ctl config migrate_to_db"
```

This must be done when Akkoma is running!

References:

This PR to Pleroma YNH (uncommited)
https://github.com/bugsysop/pleroma_ynh/blob/config-migrate-to-db/scripts/install#L272

Source file in my fork
https://github.com/YunoHost-Apps/pleroma_ynh/pull/224/commits/0eb448262616d075082038729d8c40a213e37d75

**Comment by bugsysop** [comment]
I also think you must make two separate commits: one for DB confing, one for Mangane install... More easy to manage and debug

**Comment by bugsysop** [comment]
## Correction 

On line 211 of your install script you have the correct change to the config file about activation of DB confing and after line 277 you have the intended command to activate...

This must work correctly... Forgive me to don't check this before commenting

**Comment by lapineige** [comment]
> This must work correctly... Forgive me to don't check this before commenting

I made the same "mistake", tested the command and it seems to be correct indeed :sweat_smile:

And CI doesn't report the same issue as when the command was erroneous…

**Comment by lapineige** [comment]
@ericgaspar why did you remove "based on Pleroma" from the description ?
As it is relatively new and not well know, I believe it's better to keep this guidance for our users to choose…

**Comment by ericgaspar** [comment]
With the new webadmin app catalog, we need to make description shot. I will use the DESCRIPTION.md instead for in depth explanation...

**Comment by lapineige** [comment]
I didn't know that, is there an hard character limit or something ?

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Here we go, it's working :)

> Should do it on upgrade and restore too ?

I don't think so for upgrades, the setting is already there.

But for restores ?
@bugsysop do you know how it's handled on the Pleroma side, is that setting backed up and restored without any restore script intervention ?

**Comment by lapineige** [comment]
> We should document Mangane in the readme.

Will be done later, I'm merging this first.

Mangane may because the default, hence I won't write documentation that will change pretty soon.

**Comment by lapineige** [comment]
CI:
> ============================================
  [Test 3/6] (Test complet) Installation in private mode
 ============================================
> Error: In use
Running: yunohost app install --force /app_folder -a "domain=sub.domain.tld&is_public=0&admin=package_checker&password=1Strong-Password&name=My_Pleroma&registration=0&cache=1&size=2g&path=/&"
2604 ERROR akkoma is already installed
Error: Installation failed.

Does someone know what's happening ?

> SUCCESS Restoration completed
>  Validating that the app akkoma can/can't be accessed with its URL...
> Error: Failed unmounting instance: In use
>
>  The following apps can't be restored because they are already installed: akkoma

Wait what ?

**Pull request merged**
