### PR TITLE
Remove `config migrate_to_db`

### PR DESCRIPTION
**Pull request by bugsysop**
See #25

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
If I understand it correctly, as long as this command is run once, then it will kept being applied in the future ?

I'm also still a bit unsure of what it is doing. Does that tells akkoma to use the config file values ?

**Comment by bugsysop** [comment]
This command must be run at install, to insert the values from the _config file_ created by YNH in the data base (ex. path to `static/` directory).

This PR stop running it at every upgrade, because this eraze _all customization_ made to Pleroma/Akkoma config via the Admin interface (custom frontend, max file size, etc.).

**Comment by bugsysop** [comment]
> Does that mean that afterwards altering the config file will have no impact on the instance, and that all changes must be done in the admin UI ?

Yes !

> Because it uses the config file content to overwrite it, I guess ?

Obviously ;-)

**Comment by lapineige** [comment]
> > Does that mean that afterwards altering the config file will have no impact on the instance, and that all changes must be done in the admin UI ?
> 
> Yes !

Ooooo that explains why my tests were failing 😅
So how can we change settings afterwards during upgrade ? 🤔

**Comment by lapineige** [comment]
!testme

**Comment by bugsysop** [comment]
> So how can we change settings afterwards during upgrade ? 🤔

If I remember well there is no command to migrate config from DB to config file...

**Comment by lapineige** [comment]
And any command to apply a setting directly from the command line ?

**Comment by lapineige** [comment]
From the CI, we can retrieve some information for the packaging v2 about the peak RAM usage… but it varies from 850MB up to 2200MB 😱 🤔

**Comment by lapineige** [comment]
Manual upgrade went fine as far as I can tell.

**Comment by joeldebruijn** [comment]
> Manual upgrade went fine as far as I can tell. Still have a `Request failed with status code 404 - Not implemented` failure on admin UI.

Same here, upgraded via YunoHost webadmin but still the same errors.
Does it need a one-time-once-again manual edit of the config file?

Just trying to understand as a noob tho. 😇😊

**Comment by lapineige** [comment]
I don't really know, I need to try again and focus on it for a while to be able to dig into that issue, and I don't have the time for that currently.

(Maybe we should open a separate issue)

**Pull request merged**
