### PR TITLE
v3.6.0

### LINKED ISSUE #20: Upgrade to new stable version
Maybe can we begin to test an upgrade to the new stable version of Akkoma 
https://meta.akkoma.dev/t/akkoma-stable-2023-02-lies-verifies-and-statistics/356

### PR DESCRIPTION
**Pull request by lapineige**
- Version 3.6.0 is available : https://meta.akkoma.dev/t/akkoma-stable-2023-02-lies-verifies-and-statistics/356
Full changelog : https://akkoma.dev/AkkomaGang/akkoma/src/branch/develop/CHANGELOG.md#2023-02
Fix #20 #19 
- Documentation improvements #17 
- scripts cleaning

### CODE REVIEW

**Comment by bugsysop** [comment]
At first look upgrade to `testing` branch worked like a charm

I have one warning about YNH App:

```
Warning: Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```

And some warnings about Akkoma:

```
Warning: Feb 14 21:09:27 pleroma[614806]: xx:xx:xx.xxx [warning] Metric type summary is unsupported. Dropping measure. metric_name:=[:phoenix, :endpoint, :stop, :duration]
```

**Comment by bugsysop** [comment]
Can't access anymore to Admin FE

```
Request failed with status code 404 - Not implemented
```

Maybe related to this other entry in the logs:

```
Warning: File /etc/akkoma/config.exs has been manually modified since the installation or last upgrade. So it has been duplicated in /var/cache/yunohost/appconfbackup//etc/akkoma/config.exs.backup.20230214.210907
```

**Comment by lapineige** [comment]
Same issue, I didn't have the time to investigate yet.




> And some warnings about Akkoma:
> 
> ```
> Warning: Feb 14 21:09:27 pleroma[614806]: xx:xx:xx.xxx [warning] Metric type summary is unsupported. Dropping measure. metric_name:=[:phoenix, :endpoint, :stop, :duration]
> ```


I'm made a diff, they are the same.

Also no error reported by akkoma service.

**Comment by lapineige** [comment]
> The Magane frontent is also gone...

Mangane is still there in my case :thinking:

**Comment by bugsysop** [comment]
Made a fresh install of `testing` branch, Akkoma working fine...

**Comment by lapineige** [comment]
This is getting mysterious…

**Comment by lapineige** [comment]
Last time the issue with admin-fe was something with the config file, but it hasn't changed…

**Comment by lucyferu** [comment]
tried to install using `sudo yunohost app install https://github.com/YunoHost-Apps/akkoma_ynh/tree/testing --debug` after the regular install through web-admin page didn't work.

the first message i got was: 
```
DANGER! This app is not part of YunoHost's app catalog. Installing third-party a
pps may compromise the integrity and security of your system. You should probabl
y NOT install it unless you know what you are doing. NO SUPPORT will be provided
 if this app doesn't work or breaks your system... If you are willing to take th
at risk anyway, type 'Yes, I understand':
```

is this normal?

anyway, it failed again:` 498585 ERROR The operation 'Install the 'akkoma' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230214-225925-app_install-akkoma' to get help`

and [this here](https://paste.yunohost.org/raw/idamafuciv) is the log. 😢

**Comment by lapineige** [comment]
Just in case : did you use any special character in the password ?

**Comment by bugsysop** [comment]
Opened an issue here #23 about _config parameters_ problems

**Comment by bugsysop** [comment]
>Just in case : did you use any special character in the password ?

Nein !

**Comment by bugsysop** [comment]
@lucyferu 

``` 
DANGER! This app is not part of YunoHost's app catalog. Installing third-party a
pps may compromise the integrity and security of your system. You should probabl
y NOT install it unless you know what you are doing. NO SUPPORT will be provided
 if this app doesn't work or breaks your system... If you are willing to take th
at risk anyway, type 'Yes, I understand':
```

This is normal because you try to install the `testing` branch

For your install problem, maybe verify that there is no residual **akkoma** directory here: `/home/yunohost.app/`

**Comment by lucyferu** [comment]
> did you use any special character in the password ?

yes, should i not?



> maybe verify that there is no residual **akkoma** directory here: `/home/yunohost.app/`

there is one. should i remove it before trying agian?

**Comment by lapineige** [comment]
> > did you use any special character in the password ?
> 
> yes, should i not?

Indeed, because of an unresolved bug. See : #4 
I believe that's your issue right now.

> > maybe verify that there is no residual **akkoma** directory here: `/home/yunohost.app/`
> 
> there is one. should i remove it before trying agian?

Yes, just in case. It is not removed as it contains important data (media uploads, ...) that should not be removed in case of failed upgrade an so on (it is not backed up).
In the future thanks to #22 it will be documented in the readme/uninstall log.

**Comment by lucyferu** [comment]
[it failed](https://paste.yunohost.org/raw/ecuketimuw) again 😿

**Comment by lapineige** [comment]
Ok so the source archive changed again ! 🤔

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
The OTP version number didn't change in the related archive.
I don't know what they done, so I can't check if this is legitimate or a malicious. Considering the very recent release I suppose it's a fix or similar.
You may try it again.

We definitely need to do #2.

**Comment by lapineige** [comment]
@bugsysop oh you're right, Mangane is gone, that was a cache issue…

**Comment by lucyferu** [comment]
i tried again and it finally worked!
i have akkoma!
thank you very much. 💟

**Pull request merged**
